# i3blocks configuration file
#
# The i3blocks man page describes the usage of the binary,
# and its website describes the configuration:
#
#     https://vivien.github.io/i3blocks

script_dir=/home/pabrax/.config/i3/scripts

# Global properties
separator=true
align=center
markup=pango
color=#000000
background=#0fb2eb
separator_block_width=10


# [documentation]
# full_text=Documentation
# website=https://vivien.github.io/i3blocks
# command=xdg-open "$website"


[wireless_ip]
command=ip addr show wlan0 | grep 'inet ' | awk '{print " " $2}' | cut -d'/' -f1
interval=once
color=#91E78B


[ethernet_ip]
command=ip addr show enp24s0 | grep 'inet ' | awk '{print "󰈀 " $2}' | cut -d'/' -f1
interval=once
separator=true
min_width=125
background=#c330b2
color=#ffffff

[disk]
command=$script_dir/disk.sh
interval=10
min_width=75

[date]
command=date '+%Y-%m-%d'
interval=60
min_width=80

[time]
command=date '+"%H:%M"'
interval=1
min_width=50


## enable if use laptop
# [battery]
# command=$script_dir/battery.sh
# interval=60

# Print click data
[powermenu]
full_text=" 󰿅 "
button_click=1
command=$script_dir/powermenu.sh
min_width=30

