## Colors configuration
[colors.primary]
background = "#070707"
foreground = "#ffffff"

[colors.normal]
black   = "#01161b"
red     = "#ff5959"
green   = "#71c64e"
yellow  = "#ffeb7a"
blue    = "#04acb5"
magenta = "#313033"
cyan    = "#4ac5e8"
white   = "#a3b5b8"

[colors.bright]
black   = "#878f91"
red     = "#ff5959"
green   = "#01161b"
yellow  = "#71c64e"
blue    = "#ffeb7a"
magenta = "#04acb5"
cyan    = "#b04ae8"
white   = "#cecece"
