## Colors configuration
[colors.primary]
background = "#1a1b26"
foreground = "#f1fcf9"

[colors.normal]
black   = "#20262c"
red     = "#bb9af7"
green   = "#74dd91"
yellow  = "#e0af68"
blue    = "#9ece6a"
magenta = "#7aa2f7"
cyan    = "#b4f9f8"
white   = "#f1fcf9"

[colors.bright]
black   = "#414868"
red     = "#bb9af7"
green   = "#4bc66d"
yellow  = "#db695b"
blue    = "#3dbac2"
magenta = "#bb9af7"
cyan    = "#62cdcd"
white   = "#e0e5e5"
