## Colors configuration
[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.normal]
black   = "#121212"
red     = "#9f6666"
green   = "#c1c1c1"
yellow  = "#999999"
blue    = "#5f8787"
magenta = "#313033"
cyan    = "#aaaaaa"
white   = "#a3b5b8"

[colors.bright]
black   = "#878f91"
red     = "#dd9998"
green   = "#01161b"
yellow  = "##888888"
blue    = "##aaaaaa"
magenta = "#5f8787"
cyan    = "##c1c1c1"
white   = "#cecece"
