#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/bspwm"
STYLE="dark_horizon"
RASI="$DIR/themes/$STYLE/rofi/windows.rasi"

# Run
rofi \
    -show window \
	-theme ${RASI}
